// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcfWE2rZtmjv0ZfwbD9Rb4koDH2uPI1Po',
    appId: '1:832786580609:web:a05bb0bd1f9454424a3980',
    messagingSenderId: '832786580609',
    projectId: 'fir-login-22863',
    authDomain: 'fir-login-22863.firebaseapp.com',
    storageBucket: 'fir-login-22863.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPYAHiEjNul5W4pTvg8C_jjCtii_QosbA',
    appId: '1:832786580609:android:a0e98a84112adab24a3980',
    messagingSenderId: '832786580609',
    projectId: 'fir-login-22863',
    storageBucket: 'fir-login-22863.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIoaGGWL9nGmI_DYJMV9nyTntXmjcwiUE',
    appId: '1:832786580609:ios:bdaa55aaa1f823784a3980',
    messagingSenderId: '832786580609',
    projectId: 'fir-login-22863',
    storageBucket: 'fir-login-22863.appspot.com',
    iosBundleId: 'com.example.firebaseLogin',
  );
}
